export type Language =
  | "en"
  | "hi"
  | "ta"
  | "te"
  | "bn"
  | "mr"
  | "gu"
  | "kn"
  | "ml"
  | "pa"
  | "ur";

export const languages: Record<Language, { name: string; nativeName: string }> =
  {
    en: { name: "English", nativeName: "English" },
    hi: { name: "Hindi", nativeName: "हिंदी" },
    ta: { name: "Tamil", nativeName: "தமிழ்" },
    te: { name: "Telugu", nativeName: "తెలుగు" },
    bn: { name: "Bengali", nativeName: "বাংলা" },
    mr: { name: "Marathi", nativeName: "मराठी" },
    gu: { name: "Gujarati", nativeName: "ગુજરાતી" },
    kn: { name: "Kannada", nativeName: "ಕನ್ನಡ" },
    ml: { name: "Malayalam", nativeName: "മലയാളം" },
    pa: { name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
    ur: { name: "Urdu", nativeName: "اردو" },
  };

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    dashboard: "Dashboard",

    // Home page
    title: "CivicPulse",
    subtitle:
      "AI-Driven Grievance Redressal System. Report issues, track status, and improve your city.",
    reportTitle: "Report a Grievance",
    reportDesc:
      "Describe the issue you are facing. Our AI will automatically categorize and route it to the right department.",
    fieldLabel: "Title",
    descLabel: "Description",
    submit: "Submit Grievance",
    submitting: "Submitting...",
    success: "Grievance submitted successfully!",
    error: "Failed to submit grievance.",
    adminLink: "Admin Portal",
    fieldLink: "Field Officer Portal",
    features: "Why use CivicPulse?",
    feature1: "AI-Powered Routing",
    feature1Desc: "Automatically sends your report to the right department.",
    feature2: "Real-time Tracking",
    feature2Desc: "Monitor the status of your grievance every step of the way.",
    feature3: "Quick Resolution",
    feature3Desc: "Our streamlined process ensures faster response times.",
    consentText:
      "I consent to the processing of my data for grievance redressal.",
    location: "Location",
    regionCode: "Region Code",
    uploadEvidence: "Upload Evidence (Optional)",
    titlePlaceholder: "e.g., Water leakage in Main St.",
    descPlaceholder: "Provide more details...",

    // Admin
    adminConsole: "Admin Console",
    grievances: "Grievances",
    kanbanBoard: "Kanban Board",
    settings: "Settings",
    totalGrievances: "Total Grievances",
    openGrievances: "Open Grievances",
    resolvedGrievances: "Resolved Grievances",
    criticalGrievances: "Critical Grievances",

    // Field Officer
    myTasks: "My Tasks",
    startProgress: "Start Progress",
    resolve: "Resolve",
    uploadProof: "Upload Proof",

    // Common
    status: "Status",
    priority: "Priority",
    category: "Category",
    createdAt: "Created At",
    viewDetails: "View Details",
    trackStatus: "Track Status",
  },
  hi: {
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉग आउट",
    dashboard: "डैशबोर्ड",
    title: "CivicPulse (नागरिक पल्स)",
    subtitle:
      "एआई-संचालित शिकायत निवारण प्रणाली। समस्याओं की रिपोर्ट करें, स्थिति ट्रैक करें और अपने शहर को बेहतर बनाएं।",
    reportTitle: "शिकायत दर्ज करें",
    reportDesc:
      "जिस समस्या का आप सामना कर रहे हैं उसका वर्णन करें। हमारा एआई इसे स्वचालित रूप से वर्गीकृत करेगा और सही विभाग को भेजेगा।",
    fieldLabel: "शीर्षक",
    descLabel: "विवरण",
    submit: "शिकायत जमा करें",
    submitting: "जमा हो रहा है...",
    success: "शिकायत सफलतापूर्वक जमा की गई!",
    error: "शिकायत जमा करने में विफल।",
    adminLink: "एडमिन पोर्टल",
    fieldLink: "फील्ड अधिकारी पोर्टल",
    features: "CivicPulse क्यों चुनें?",
    feature1: "एआई-संचालित रूटिंग",
    feature1Desc: "आपकी रिपोर्ट को स्वचालित रूप से सही विभाग में भेजता है।",
    feature2: "रियल-टाइम ट्रैकिंग",
    feature2Desc: "हर कदम पर अपनी शिकायत की स्थिति की निगरानी करें।",
    feature3: "त्वरित समाधान",
    feature3Desc:
      "हमारी सुव्यवस्थित प्रक्रिया तेजी से प्रतिक्रिया समय सुनिश्चित करती है।",
    consentText:
      "मैं शिकायत निवारण के लिए अपने डेटा के प्रसंस्करण के लिए सहमति देता हूं।",
    location: "स्थान",
    regionCode: "क्षेत्र कोड",
    uploadEvidence: "साक्ष्य अपलोड करें (वैकल्पिक)",
    titlePlaceholder: "उदाहरण: मुख्य सड़क पर पानी का रिसाव",
    descPlaceholder: "अधिक विवरण प्रदान करें...",
    adminConsole: "एडमिन कंसोल",
    grievances: "शिकायतें",
    kanbanBoard: "कानबान बोर्ड",
    settings: "सेटिंग्स",
    totalGrievances: "कुल शिकायतें",
    openGrievances: "खुली शिकायतें",
    resolvedGrievances: "निपटाई गई शिकायतें",
    criticalGrievances: "गंभीर शिकायतें",
    myTasks: "मेरे कार्य",
    startProgress: "प्रगति शुरू करें",
    resolve: "समाधान करें",
    uploadProof: "साक्ष्य अपलोड करें",
    status: "स्थिति",
    priority: "प्राथमिकता",
    category: "श्रेणी",
    createdAt: "बनाया गया",
    viewDetails: "विवरण देखें",
    trackStatus: "स्थिति ट्रैक करें",
  },
  ta: {
    login: "உள்நுழை",
    signup: "பதிவு செய்க",
    logout: "வெளியேற",
    dashboard: "டாஷ்போர்டு",
    title: "CivicPulse",
    subtitle:
      "AI-இயக்கப்பட்ட புகாரை தீர்க்கும் அமைப்பு. சிக்கல்களைப் புகாரளிக்கவும், நிலையைக் கண்காணிக்கவும், உங்கள் நகரத்தை மேம்படுத்தவும்.",
    reportTitle: "புகார் செய்ய",
    reportDesc:
      "நீங்கள் எதிர்கொள்ளும் சிக்கலை விவரிக்கவும். எங்கள் AI அதை தானாக வகைப்படுத்தி சரியான துறைக்கு அனுப்பும்.",
    fieldLabel: "தலைப்பு",
    descLabel: "விளக்கம்",
    submit: "புகாரை சமர்ப்பிக்க",
    submitting: "சமர்ப்பிக்கப்படுகிறது...",
    success: "புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
    error: "புகாரை சமர்ப்பிக்க முடியவில்லை.",
    adminLink: "நிர்வாக போர்டல்",
    fieldLink: "கள அலுவலர் போர்டல்",
    features: "ஏன் CivicPulse பயன்படுத்த?",
    feature1: "AI-இயக்கப்பட்ட ரூட்டிங்",
    feature1Desc: "உங்கள் அறிக்கையை தானாக சரியான துறைக்கு அனுப்புகிறது.",
    feature2: "நேரடி கண்காணிப்பு",
    feature2Desc: "ஒவ்வொரு படியிலும் உங்கள் புகாரின் நிலையைக் கண்காணிக்கவும்.",
    feature3: "விரைவான தீர்வு",
    feature3Desc:
      "எங்கள் சீராக்கப்பட்ட செயல்முறை வேகமான பதிலளிப்பு நேரத்தை உறுதி செய்கிறது.",
    consentText:
      "புகாரை தீர்க்கும் நோக்கத்திற்காக எனது தரவை செயலாக்குவதற்கு நான் ஒப்புக்கொள்கிறேன்.",
    location: "இடம்",
    regionCode: "மண்டல குறியீடு",
    uploadEvidence: "சான்று பதிவேற்ற (விருப்பமானது)",
    adminConsole: "நிர்வாக கன்சோல்",
    grievances: "புகார்கள்",
    kanbanBoard: "கன்பான் பலகை",
    settings: "அமைப்புகள்",
    totalGrievances: "மொத்த புகார்கள்",
    openGrievances: "திறந்த புகார்கள்",
    resolvedGrievances: "தீர்க்கப்பட்ட புகார்கள்",
    criticalGrievances: "முக்கிய புகார்கள்",
    myTasks: "எனது பணிகள்",
    startProgress: "முன்னேற்றத்தைத் தொடங்க",
    resolve: "தீர்க்க",
    uploadProof: "சான்று பதிவேற்ற",
    status: "நிலை",
    priority: "முன்னுரிமை",
    category: "வகை",
    createdAt: "உருவாக்கப்பட்டது",
    viewDetails: "விவரங்களைக் காண்க",
    trackStatus: "நிலையைக் கண்காணிக்க",
  },
  te: {
    login: "ప్రవేశించండి",
    signup: "సైన్ అప్",
    logout: "లాగ్అవుట్",
    dashboard: "డాష్బోర్డ్",
    title: "CivicPulse",
    subtitle:
      "AI-నడిచే ఫిర్యాదు పరిష్కార వ్యవస్థ. సమస్యలను నివేదించండి, స్థితిని ట్రాక్ చేయండి మరియు మీ నగరాన్ని మెరుగుపరచండి.",
    reportTitle: "ఫిర్యాదు చేయండి",
    reportDesc:
      "మీరు ఎదుర్కొంటున్న సమస్యను వివరించండి. మా AI దానిని స్వయంచాలకంగా వర్గీకరిస్తుంది మరియు సరైన శాఖకు మారుస్తుంది.",
    fieldLabel: "శీర్షిక",
    descLabel: "వివరణ",
    submit: "ఫిర్యాదును సమర్పించండి",
    submitting: "సమర్పిస్తోంది...",
    success: "ఫిర్యాదు విజయవంతంగా సమర్పించబడింది!",
    error: "ఫిర్యాదును సమర్పించడంలో విఫలమైంది.",
    adminLink: "అడ్మిన్ పోర్టల్",
    fieldLink: "ఫీల్డ్ ఆఫీసర్ పోర్టల్",
    features: "CivicPulse ఎందుకు ఉపయోగించాలి?",
    feature1: "AI-నడిచే రూటింగ్",
    feature1Desc: "మీ నివేదికను స్వయంచాలకంగా సరైన శాఖకు పంపుతుంది.",
    feature2: "రియల్-టైమ్ ట్రాకింగ్",
    feature2Desc: "ప్రతి అడుగులో మీ ఫిర్యాదు స్థితిని పర్యవేక్షించండి.",
    feature3: "వేగవంతమైన పరిష్కారం",
    feature3Desc:
      "మా క్రమబద్ధమైన ప్రక్రియ వేగవంతమైన ప్రతిస్పందన సమయాన్ని నిర్ధారిస్తుంది.",
    consentText:
      "ఫిర్యాదు పరిష్కారం కోసం నా డేటా ప్రాసెసింగ్‌కు నేను సమ్మతిస్తున్నాను.",
    location: "స్థానం",
    regionCode: "ప్రాంత కోడ్",
    uploadEvidence: "ఆధారం అప్‌లోడ్ చేయండి (ఐచ్ఛికం)",
    adminConsole: "అడ్మిన్ కన్సోల్",
    grievances: "ఫిర్యాదులు",
    kanbanBoard: "కాన్బాన్ బోర్డ్",
    settings: "సెట్టింగ్‌లు",
    totalGrievances: "మొత్తం ఫిర్యాదులు",
    openGrievances: "తెరిచిన ఫిర్యాదులు",
    resolvedGrievances: "పరిష్కరించిన ఫిర్యాదులు",
    criticalGrievances: "క్రిటికల్ ఫిర్యాదులు",
    myTasks: "నా పనులు",
    startProgress: "ప్రగతిని ప్రారంభించండి",
    resolve: "పరిష్కరించండి",
    uploadProof: "ఆధారం అప్‌లోడ్ చేయండి",
    status: "స్థితి",
    priority: "అధిక ప్రాధాన్యత",
    category: "వర్గం",
    createdAt: "సృష్టించబడింది",
    viewDetails: "వివరాలను చూడండి",
    trackStatus: "స్థితిని ట్రాక్ చేయండి",
  },
  bn: {
    login: "লগইন",
    signup: "সাইন আপ",
    logout: "লগআউট",
    dashboard: "ড্যাশবোর্ড",
    title: "CivicPulse",
    subtitle:
      "AI-চালিত অভিযোগ প্রতিকার ব্যবস্থা। সমস্যার রিপোর্ট করুন, স্থিতি ট্র্যাক করুন এবং আপনার শহর উন্নত করুন।",
    reportTitle: "অভিযোগ করুন",
    reportDesc:
      "আপনার যে সমস্যার সম্মুখীন হচ্ছেন তার বর্ণনা দিন। আমাদের AI স্বয়ংক্রিয়ভাবে এটি শ্রেণীবদ্ধ করবে এবং সঠিক বিভাগে পাঠাবে।",
    fieldLabel: "শিরোনাম",
    descLabel: "বিবরণ",
    submit: "অভিযোগ জমা দিন",
    submitting: "জমা দেওয়া হচ্ছে...",
    success: "অভিযোগ সফলভাবে জমা দেওয়া হয়েছে!",
    error: "অভিযোগ জমা দিতে ব্যর্থ।",
    adminLink: "অ্যাডমিন পোর্টাল",
    fieldLink: "ফিল্ড অফিসার পোর্টাল",
    features: "কেন CivicPulse ব্যবহার করবেন?",
    feature1: "AI-চালিত রাউটিং",
    feature1Desc: "স্বয়ংক্রিয়ভাবে আপনার রিপোর্ট সঠিক বিভাগে পাঠায়।",
    feature2: "রিয়েল-টাইম ট্র্যাকিং",
    feature2Desc: "প্রতিটি ধাপে আপনার অভিযোগের স্থিতি পর্যবেক্ষণ করুন।",
    feature3: "দ্রুত সমাধান",
    feature3Desc:
      "আমাদের সুসংহত প্রক্রিয়া দ্রুত প্রতিক্রিয়া সময় নিশ্চিত করে।",
    consentText:
      "অভিযোগ প্রতিকারের জন্য আমার ডেটা প্রক্রিয়াকরণে আমি সম্মতি দিচ্ছি।",
    location: "অবস্থান",
    regionCode: "অঞ্চল কোড",
    uploadEvidence: "প্রমাণ আপলোড করুন (ঐচ্ছিক)",
    adminConsole: "অ্যাডমিন কনসোল",
    grievances: "অভিযোগ",
    kanbanBoard: "কানবান বোর্ড",
    settings: "সেটিংস",
    totalGrievances: "মোট অভিযোগ",
    openGrievances: "খোলা অভিযোগ",
    resolvedGrievances: "সমাধানকৃত অভিযোগ",
    criticalGrievances: "সমালোচনামূলক অভিযোগ",
    myTasks: "আমার কাজ",
    startProgress: "প্রগতি শুরু করুন",
    resolve: "সমাধান করুন",
    uploadProof: "প্রমাণ আপলোড করুন",
    status: "স্থিতি",
    priority: "অগ্রাধিকার",
    category: "বিভাগ",
    createdAt: "তৈরি হয়েছে",
    viewDetails: "বিবরণ দেখুন",
    trackStatus: "স্থিতি ট্র্যাক করুন",
  },
  mr: {
    login: "लॉगइन",
    signup: "साइन अप",
    logout: "लॉगआउट",
    dashboard: "डॅशबोर्ड",
    title: "CivicPulse",
    subtitle:
      "AI-चालित तक्रार निवारण प्रणाली. समस्यांची अहवाल द्या, स्थिती ट्रॅक करा आणि आपले शहर सुधारा.",
    reportTitle: "तक्रार करा",
    reportDesc:
      "आपण ज्या समस्येचा सामना करत आहात तिचे वर्णन करा. आमची AI ती स्वयंचलितपणे वर्गीकृत करेल आणि योग्य विभागात पाठवेल.",
    fieldLabel: "शीर्षक",
    descLabel: "वर्णन",
    submit: "तक्रार सबमिट करा",
    submitting: "सबमिट होत आहे...",
    success: "तक्रार यशस्वीरित्या सबमिट झाली!",
    error: "तक्रार सबमिट करण्यात अयशस्वी.",
    adminLink: "अॅडमिन पोर्टल",
    fieldLink: "फील्ड ऑफिसर पोर्टल",
    features: "CivicPulse का वापर?",
    feature1: "AI-चालित राउटिंग",
    feature1Desc: "आपला अहवाल स्वयंचलितपणे योग्य विभागात पाठवतो.",
    feature2: "रीअल-टाइम ट्रॅकिंग",
    feature2Desc: "प्रत्येक टप्प्यावर आपल्या तक्रारीची स्थिती निरीक्षण करा.",
    feature3: "त्वरित निराकरण",
    feature3Desc:
      "आमची सुव्यवस्थित प्रक्रिया वेगवान प्रतिसाद वेळ सुनिश्चित करते.",
    consentText:
      "तक्रार निवारणासाठी माझ्या डेटाच्या प्रक्रियेसाठी मी संमती देतो.",
    location: "स्थान",
    regionCode: "प्रदेश कोड",
    uploadEvidence: "पुरावा अपलोड करा (पर्यायी)",
    adminConsole: "अॅडमिन कन्सोल",
    grievances: "तक्रारी",
    kanbanBoard: "कानबान बोर्ड",
    settings: "सेटिंग्ज",
    totalGrievances: "एकूण तक्रारी",
    openGrievances: "उघड्या तक्रारी",
    resolvedGrievances: "निराकरण केलेल्या तक्रारी",
    criticalGrievances: "गंभीर तक्रारी",
    myTasks: "माझी कामे",
    startProgress: "प्रगती सुरू करा",
    resolve: "निराकरण करा",
    uploadProof: "पुरावा अपलोड करा",
    status: "स्थिती",
    priority: "प्राधान्य",
    category: "श्रेणी",
    createdAt: "तयार केले",
    viewDetails: "तपशील पहा",
    trackStatus: "स्थिती ट्रॅक करा",
  },
  gu: {
    login: "લૉગઇન",
    signup: "સાઇન અપ",
    logout: "લૉગઆઉટ",
    dashboard: "ડેશબોર્ડ",
    title: "CivicPulse",
    subtitle:
      "AI-સંચાલિત ફરિયાદ નિવારણ સિસ્ટમ. સમસ્યાઓની અહેવાલ આપો, સ્થિતિ ટ્રૅક કરો અને તમારા શહેરને સુધારો.",
    reportTitle: "ફરિયાદ કરો",
    reportDesc:
      "તમે જે સમસ્યાનો સામનો કરી રહ્યા છો તેનું વર્ણન કરો. અમારી AI તેને આપમેળે વર્ગીકૃત કરશે અને યોગ્ય વિભાગમાં મોકલશે.",
    fieldLabel: "શીર્ષક",
    descLabel: "વર્ણન",
    submit: "ફરિયાદ સબમિટ કરો",
    submitting: "સબમિટ થઈ રહ્યું છે...",
    success: "ફરિયાદ સફળતાપૂર્વક સબમિટ થઈ!",
    error: "ફરિયાદ સબમિટ કરવામાં નિષ્ફળ.",
    adminLink: "એડમિન પોર્ટલ",
    fieldLink: "ફીલ્ડ ઓફિસર પોર્ટલ",
    features: "CivicPulse શા માટે ઉપયોગ કરો?",
    feature1: "AI-સંચાલિત રૂટિંગ",
    feature1Desc: "તમારા અહેવાલને આપમેળે યોગ્ય વિભાગમાં મોકલે છે.",
    feature2: "રીઅલ-ટાઇમ ટ્રૅકિંગ",
    feature2Desc: "દરેક પગલામાં તમારી ફરિયાદની સ્થિતિનું નિરીક્ષણ કરો.",
    feature3: "ઝડપી નિવારણ",
    feature3Desc:
      "અમારી સુવ્યવસ્થિત પ્રક્રિયા ઝડપી પ્રતિક્રિયા સમય સુનિશ્ચિત કરે છે.",
    consentText:
      "ફરિયાદ નિવારણ માટે મારા ડેટાની પ્રક્રિયા માટે હું સંમતિ આપું છું.",
    location: "સ્થાન",
    regionCode: "પ્રદેશ કોડ",
    uploadEvidence: "સાક્ષ્ય અપલોડ કરો (વૈકલ્પિક)",
    adminConsole: "એડમિન કન્સોલ",
    grievances: "ફરિયાદો",
    kanbanBoard: "કાનબાન બોર્ડ",
    settings: "સેટિંગ્સ",
    totalGrievances: "કુલ ફરિયાદો",
    openGrievances: "ખુલ્લી ફરિયાદો",
    resolvedGrievances: "નિવારિત ફરિયાદો",
    criticalGrievances: "મહત્વપૂર્ણ ફરિયાદો",
    myTasks: "મારા કાર્યો",
    startProgress: "પ્રગતિ શરૂ કરો",
    resolve: "નિવારણ કરો",
    uploadProof: "સાક્ષ્ય અપલોડ કરો",
    status: "સ્થિતિ",
    priority: "પ્રાથમિકતા",
    category: "શ્રેણી",
    createdAt: "બનાવ્યું",
    viewDetails: "વિગતો જુઓ",
    trackStatus: "સ્થિતિ ટ્રૅક કરો",
  },
  kn: {
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    logout: "ಲಾಗ್‌ಔಟ್",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    title: "CivicPulse",
    subtitle:
      "AI-ನಿರ್ದೇಶಿತ ದೂರು ಪರಿಹಾರ ವ್ಯವಸ್ಥೆ. ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ, ಸ್ಥಿತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ನಗರವನ್ನು ಸುಧಾರಿಸಿ.",
    reportTitle: "ದೂರು ಮಾಡಿ",
    reportDesc:
      "ನೀವು ಎದುರಿಸುತ್ತಿರುವ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ. ನಮ್ಮ AI ಅದನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ವರ್ಗೀಕರಿಸುತ್ತದೆ ಮತ್ತು ಸರಿಯಾದ ಇಲಾಖೆಗೆ ಕಳುಹಿಸುತ್ತದೆ.",
    fieldLabel: "ಶೀರ್ಷಿಕೆ",
    descLabel: "ವಿವರಣೆ",
    submit: "ದೂರನ್ನು ಸಲ್ಲಿಸಿ",
    submitting: "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    success: "ದೂರು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!",
    error: "ದೂರನ್ನು ಸಲ್ಲಿಸಲು ವಿಫಲವಾಗಿದೆ.",
    adminLink: "ಆಡ್ಮಿನ್ ಪೋರ್ಟಲ್",
    fieldLink: "ಫೀಲ್ಡ್ ಆಫೀಸರ್ ಪೋರ್ಟಲ್",
    features: "CivicPulse ಅನ್ನು ಏಕೆ ಬಳಸಬೇಕು?",
    feature1: "AI-ನಿರ್ದೇಶಿತ ರೂಟಿಂಗ್",
    feature1Desc: "ನಿಮ್ಮ ವರದಿಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸರಿಯಾದ ಇಲಾಖೆಗೆ ಕಳುಹಿಸುತ್ತದೆ.",
    feature2: "ರಿಯಲ್-ಟೈಮ್ ಟ್ರ್ಯಾಕಿಂಗ್",
    feature2Desc: "ಪ್ರತಿ ಹಂತದಲ್ಲಿ ನಿಮ್ಮ ದೂರಿನ ಸ್ಥಿತಿಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.",
    feature3: "ತ್ವರಿತ ಪರಿಹಾರ",
    feature3Desc:
      "ನಮ್ಮ ಸುಸಂಘಟಿತ ಪ್ರಕ್ರಿಯೆ ವೇಗವಾದ ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯವನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ.",
    consentText:
      "ದೂರು ಪರಿಹಾರಕ್ಕಾಗಿ ನನ್ನ ಡೇಟಾದ ಪ್ರಕ್ರಿಯೆಗೆ ನಾನು ಸಮ್ಮತಿಸುತ್ತೇನೆ.",
    location: "ಸ್ಥಳ",
    regionCode: "ಪ್ರದೇಶ ಕೋಡ್",
    uploadEvidence: "ಪುರಾವೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (ಐಚ್‌ಛಿಕ)",
    adminConsole: "ಆಡ್ಮಿನ್ ಕನ್‌ಸೋಲ್",
    grievances: "ದೂರುಗಳು",
    kanbanBoard: "ಕಾನ್ಬಾನ್ ಬೋರ್ಡ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    totalGrievances: "ಒಟ್ಟು ದೂರುಗಳು",
    openGrievances: "ತೆರೆದ ದೂರುಗಳು",
    resolvedGrievances: "ಪರಿಹರಿಸಿದ ದೂರುಗಳು",
    criticalGrievances: "ಗಂಭೀರ ದೂರುಗಳು",
    myTasks: "ನನ್ನ ಕಾರ್ಯಗಳು",
    startProgress: "ಪ್ರಗತಿಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    resolve: "ಪರಿಹರಿಸಿ",
    uploadProof: "ಪುರಾವೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    status: "ಸ್ಥಿತಿ",
    priority: "ಆದ್ಯತೆ",
    category: "ವರ್ಗ",
    createdAt: "ರಚಿಸಲಾಗಿದೆ",
    viewDetails: "ವಿವರಗಳನ್ನು ನೋಡಿ",
    trackStatus: "ಸ್ಥಿತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  },
  ml: {
    login: "ലോഗിൻ",
    signup: "സൈൻ അപ്",
    logout: "ലോഗൗട്ട്",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    title: "CivicPulse",
    subtitle:
      "AI-നിയന്ത്രിത പരാതി പരിഹാര സിസ്റ്റം. പ്രശ്നങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക, നില നിരീക്ഷിക്കുക, നിങ്ങളുടെ നഗരം മെച്ചപ്പെടുത്തുക.",
    reportTitle: "പരാതി നൽകുക",
    reportDesc:
      "നിങ്ങൾ അഭിമുഖീകരിക്കുന്ന പ്രശ്നത്തെ വിവരിക്കുക. ഞങ്ങളുടെ AI അതിനെ യാന്ത്രികമായി വർഗ്ഗീകരിക്കുകയും ശരിയായ വിഭാഗത്തിലേക്ക് അയയ്ക്കുകയും ചെയ്യും.",
    fieldLabel: "ശീർഷകം",
    descLabel: "വിവരണം",
    submit: "പരാതി സമർപ്പിക്കുക",
    submitting: "സമർപ്പിക്കുന്നു...",
    success: "പരാതി വിജയകരമായി സമർപ്പിച്ചു!",
    error: "പരാതി സമർപ്പിക്കുന്നതിൽ പരാജയപ്പെട്ടു.",
    adminLink: "അഡ്മിൻ പോർട്ടൽ",
    fieldLink: "ഫീൽഡ് ഓഫീസർ പോർട്ടൽ",
    features: "CivicPulse എന്തുകൊണ്ട് ഉപയോഗിക്കണം?",
    feature1: "AI-നിയന്ത്രിത റൂട്ടിംഗ്",
    feature1Desc:
      "നിങ്ങളുടെ റിപ്പോർട്ട് യാന്ത്രികമായി ശരിയായ വിഭാഗത്തിലേക്ക് അയയ്ക്കുന്നു.",
    feature2: "റിയൽ-ടൈം ട്രാക്കിംഗ്",
    feature2Desc: "ഓരോ ഘട്ടത്തിലും നിങ്ങളുടെ പരാതിയുടെ നില നിരീക്ഷിക്കുക.",
    feature3: "വേഗത്തിലുള്ള പരിഹാരം",
    feature3Desc:
      "ഞങ്ങളുടെ സുസംഘടിത പ്രക്രിയ വേഗത്തിലുള്ള പ്രതികരണ സമയം ഉറപ്പാക്കുന്നു.",
    consentText:
      "പരാതി പരിഹാരത്തിനായി എന്റെ ഡേറ്റ പ്രോസസ്സ് ചെയ്യുന്നതിന് ഞാൻ സമ്മതിക്കുന്നു.",
    location: "സ്ഥലം",
    regionCode: "പ്രദേശം കോഡ്",
    uploadEvidence: "തെളിവ് അപ്‌ലോഡ് ചെയ്യുക (ഓപ്‌ഷണൽ)",
    adminConsole: "അഡ്മിൻ കൺസോൾ",
    grievances: "പരാതികൾ",
    kanbanBoard: "കാൻബാൻ ബോർഡ്",
    settings: "ക്രമീകരണങ്ങൾ",
    totalGrievances: "മൊത്തം പരാതികൾ",
    openGrievances: "തുറന്ന പരാതികൾ",
    resolvedGrievances: "പരിഹരിച്ച പരാതികൾ",
    criticalGrievances: "നിർണായക പരാതികൾ",
    myTasks: "എന്റെ ജോലികൾ",
    startProgress: "പുരോഗതി ആരംഭിക്കുക",
    resolve: "പരിഹരിക്കുക",
    uploadProof: "തെളിവ് അപ്‌ലോഡ് ചെയ്യുക",
    status: "നില",
    priority: "പ്രാധാന്യം",
    category: "വിഭാഗം",
    createdAt: "സൃഷ്ടിച്ചത്",
    viewDetails: "വിശദാംശങ്ങൾ കാണുക",
    trackStatus: "നില ട്രാക്ക് ചെയ്യുക",
  },
  pa: {
    login: "ਲੌਗਇਨ",
    signup: "ਸਾਈਨ ਅੱਪ",
    logout: "ਲੌਗਆਉਟ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    title: "CivicPulse",
    subtitle:
      "AI-ਸੰਚਾਲਿਤ ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਣ ਸਿਸਟਮ। ਸਮੱਸਿਆਵਾਂ ਦੀ ਰਿਪੋਰਟ ਕਰੋ, ਸਥਿਤੀ ਟ੍ਰੈਕ ਕਰੋ ਅਤੇ ਆਪਣੇ ਸ਼ਹਿਰ ਨੂੰ ਸੁਧਾਰੋ।",
    reportTitle: "ਸ਼ਿਕਾਇਤ ਕਰੋ",
    reportDesc:
      "ਉਸ ਸਮੱਸਿਆ ਦਾ ਵਰਣਨ ਕਰੋ ਜਿਸ ਦਾ ਤੁਸੀਂ ਸਾਮ੍ਹਣਾ ਕਰ ਰਹੇ ਹੋ। ਸਾਡਾ AI ਇਸਨੂੰ ਸਵੈਚਾਲਤ ਰੂਪ ਵਿੱਚ ਸ਼੍ਰੇਣੀਬੱਧ ਕਰੇਗਾ ਅਤੇ ਸਹੀ ਵਿਭਾਗ ਵਿੱਚ ਭੇਜੇਗਾ।",
    fieldLabel: "ਸਿਰਲੇਖ",
    descLabel: "ਵਰਣਨ",
    submit: "ਸ਼ਿਕਾਇਤ ਸਬਮਿਟ ਕਰੋ",
    submitting: "ਸਬਮਿਟ ਹੋ ਰਿਹਾ ਹੈ...",
    success: "ਸ਼ਿਕਾਇਤ ਸਫਲਤਾਪੂਰਵਕ ਸਬਮਿਟ ਕੀਤੀ ਗਈ!",
    error: "ਸ਼ਿਕਾਇਤ ਸਬਮਿਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।",
    adminLink: "ਐਡਮਿਨ ਪੋਰਟਲ",
    fieldLink: "ਫੀਲਡ ਅਧਿਕਾਰੀ ਪੋਰਟਲ",
    features: "CivicPulse ਕਿਉਂ ਵਰਤਣਾ ਹੈ?",
    feature1: "AI-ਸੰਚਾਲਿਤ ਰੂਟਿੰਗ",
    feature1Desc: "ਤੁਹਾਡੀ ਰਿਪੋਰਟ ਨੂੰ ਸਵੈਚਾਲਤ ਰੂਪ ਵਿੱਚ ਸਹੀ ਵਿਭਾਗ ਵਿੱਚ ਭੇਜਦਾ ਹੈ।",
    feature2: "ਰੀਅਲ-ਟਾਈਮ ਟ੍ਰੈਕਿੰਗ",
    feature2Desc: "ਹਰ ਕਦਮ 'ਤੇ ਆਪਣੀ ਸ਼ਿਕਾਇਤ ਦੀ ਸਥਿਤੀ ਦਾ ਨਿਗਰਾਨੀ ਕਰੋ।",
    feature3: "ਤੁਰੰਤ ਹੱਲ",
    feature3Desc:
      "ਸਾਡੀ ਸੁਵਿਵਸਥਿਤ ਪ੍ਰਕਿਰਿਆ ਤੇਜ਼ ਪ੍ਰਤਿਕਿਰਿਆ ਸਮਾਂ ਸੁਨਿਸ਼ਚਿਤ ਕਰਦੀ ਹੈ।",
    consentText:
      "ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਣ ਲਈ ਮੇਰੇ ਡੇਟਾ ਦੇ ਪ੍ਰੋਸੈਸਿੰਗ ਲਈ ਮੈਂ ਸਹਿਮਤੀ ਦਿੰਦਾ ਹਾਂ।",
    location: "ਸਥਾਨ",
    regionCode: "ਖੇਤਰ ਕੋਡ",
    uploadEvidence: "ਸਬੂਤ ਅਪਲੋਡ ਕਰੋ (ਵਿਕਲਪਿਕ)",
    adminConsole: "ਐਡਮਿਨ ਕੰਸੋਲ",
    grievances: "ਸ਼ਿਕਾਇਤਾਂ",
    kanbanBoard: "ਕਾਂਬਨ ਬੋਰਡ",
    settings: "ਸੈਟਿੰਗਾਂ",
    totalGrievances: "ਕੁੱਲ ਸ਼ਿਕਾਇਤਾਂ",
    openGrievances: "ਖੁੱਲ੍ਹੀਆਂ ਸ਼ਿਕਾਇਤਾਂ",
    resolvedGrievances: "ਹੱਲ ਕੀਤੀਆਂ ਸ਼ਿਕਾਇਤਾਂ",
    criticalGrievances: "ਮਹੱਤਵਪੂਰਨ ਸ਼ਿਕਾਇਤਾਂ",
    myTasks: "ਮੇਰੇ ਕੰਮ",
    startProgress: "ਪ੍ਰਗਤੀ ਸ਼ੁਰੂ ਕਰੋ",
    resolve: "ਹੱਲ ਕਰੋ",
    uploadProof: "ਸਬੂਤ ਅਪਲੋਡ ਕਰੋ",
    status: "ਸਥਿਤੀ",
    priority: "ਪ੍ਰਾਥਮਿਕਤਾ",
    category: "ਸ਼੍ਰੇਣੀ",
    createdAt: "ਬਣਾਇਆ",
    viewDetails: "ਵੇਰਵੇ ਦੇਖੋ",
    trackStatus: "ਸਥਿਤੀ ਟ੍ਰੈਕ ਕਰੋ",
  },
  ur: {
    login: "لاگ ان",
    signup: "سائن اپ",
    logout: "لاگ آؤٹ",
    dashboard: "ڈیش بورڈ",
    title: "CivicPulse",
    subtitle:
      "AI-چلنے والا شکایت حل کرنے کا نظام۔ مسائل کی رپورٹ کریں، حالت کو ٹریک کریں اور اپنے شہر کو بہتر بنائیں۔",
    reportTitle: "شکایت کریں",
    reportDesc:
      "جس مسئلے کا آپ سامنا کر رہے ہیں اس کا بیان کریں۔ ہمارا AI اسے خود کار طریقے سے درجہ بندی کرے گا اور صحیح محکمہ میں بھیجے گا۔",
    fieldLabel: "عنوان",
    descLabel: "تفصیل",
    submit: "شکایت جمع کریں",
    submitting: "جمع ہو رہا ہے...",
    success: "شکایت کامیابی سے جمع ہو گئی!",
    error: "شکایت جمع کرنے میں ناکام۔",
    adminLink: "ایڈمن پورٹل",
    fieldLink: "فیلڈ آفیسر پورٹل",
    features: "CivicPulse کیوں استعمال کریں؟",
    feature1: "AI-چلنے والا راؤٹنگ",
    feature1Desc: "آپ کی رپورٹ کو خود کار طریقے سے صحیح محکمہ میں بھیجتا ہے۔",
    feature2: "ریئل-ٹائم ٹریکنگ",
    feature2Desc: "ہر قدم پر اپنی شکایت کی حالت کی نگرانی کریں۔",
    feature3: "فوری حل",
    feature3Desc: "ہمارا مربوط عمل تیز ردعمل کے وقت کو یقینی بناتا ہے۔",
    consentText:
      "شکایت حل کرنے کے لیے اپنے ڈیٹا کی پروسیسنگ کے لیے میں رضامندی دیتا ہوں۔",
    location: "مقام",
    regionCode: "علاقہ کوڈ",
    uploadEvidence: "ثبوت اپ لوڈ کریں (اختیاری)",
    adminConsole: "ایڈمن کنسول",
    grievances: "شکایات",
    kanbanBoard: "کانبان بورڈ",
    settings: "ترتیبات",
    totalGrievances: "کل شکایات",
    openGrievances: "کھلی شکایات",
    resolvedGrievances: "حل شدہ شکایات",
    criticalGrievances: "اہم شکایات",
    myTasks: "میرے کام",
    startProgress: "ترقی شروع کریں",
    resolve: "حل کریں",
    uploadProof: "ثبوت اپ لوڈ کریں",
    status: "حالت",
    priority: "ترجیح",
    category: "زمرہ",
    createdAt: "بنایا گیا",
    viewDetails: "تفصیلات دیکھیں",
    trackStatus: "حالت ٹریک کریں",
  },
};

export function getTranslation(key: string, lang: Language): string {
  return translations[lang]?.[key] || translations.en[key] || key;
}

export function getLanguageFromStorage(): Language {
  if (typeof window === "undefined") return "en";
  const stored = localStorage.getItem("language");
  return (stored as Language) || "en";
}

export function setLanguageInStorage(lang: Language): void {
  if (typeof window === "undefined") return;
  localStorage.setItem("language", lang);
}
